### ISSUE TITLE
Can not access web page.

### ISSUE THREAD

**Issue by imbmf** [django-zfs/django-zfs#1]
Hello,
I do this:
git clone https://github.com/django-zfs/django-zfs.git
cd django-zfs
./manage.py runserver 0.0.0.0:8080
 and get this output:
[root@localhost django-zfs]# ./manage.py runserver 0.0.0.0:8080
/usr/lib/python2.7/site-packages/kombu/transport/django/models.py:9: RemovedInDjango19Warning: Model class kombu.transport.django.models.Queue doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Queue(models.Model):

/usr/lib/python2.7/site-packages/kombu/transport/django/models.py:20: RemovedInDjango19Warning: Model class kombu.transport.django.models.Message doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Message(models.Model):

/usr/lib/python2.7/site-packages/kombu/transport/django/models.py:9: RemovedInDjango19Warning: Model class kombu.transport.django.models.Queue doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Queue(models.Model):

/usr/lib/python2.7/site-packages/kombu/transport/django/models.py:20: RemovedInDjango19Warning: Model class kombu.transport.django.models.Message doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Message(models.Model):

Performing system checks...

System check identified no issues (0 silenced).
September 06, 2014 - 14:50:33
Django version 1.8.dev20140906114756, using settings 'djangozfs.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
 but can not access web page in browser.
OS = CentOS 7

**Comment by hazcod** [comment]
> Quit the server with CONTROL-C.

Might be your problem.

**Comment by FireDrunk** [comment]
If the webserver doesn't exit, and the program keeps running, the website should be visible.

Did you point your browser to 0.0.0.0:8080 ? Because 0.0.0.0 stands for "all IPv4 Addresses".
So you should actually use something like: http://192.168.0.1:8080/

**Comment by imbmf** [comment]
Hi,
thanks for suggestions if you can provide step by step instructions will be great.

**Comment by FireDrunk** [comment]
There's nothing more to it :)
If you clone the source, and install the prerequisites, it should work by just starting the webserver as you did.

Honestly i didn't test this on CentOS 7, but rather on Ubuntu. I can't think of a reason that it shouldn't work, but i guess it might be different somehow.

**Comment by imbmf** [comment]
Thanks, i will try again.
